exclude: 'docs|node_modules|migrations|.git|.tox|.idea'

repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: trailing-whitespace
        exclude_types: [svg]
    -   id: end-of-file-fixer
        exclude_types: [svg]
    -   id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        exclude: wsgi.py
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
